add ActivePool interface
blockchain-audit/meridian-starknet pull request #34
Opened 2024-06-25 12:08 UTC by ruthklirs

2024-06-25 12:44 UTC, henry-hz commented
check if open zeppelin is compatible with your last cairo

2024-06-25 12:49 UTC, ruthklirs commented
I have already added open zeppelin

2024-06-26 07:55 UTC, henry-hz requested changes

2024-06-26 07:55 UTC, henry-hz commented on src/interfaces/ItroveManager .cairo
> +//
pls fix the file name, and merge the master to your branch and run tests

2024-06-26 07:55 UTC, henry-hz commented on src/interfaces/activePool.cairo
> +#[starknet::interface]
in interfaces we start with `I` ,    IPool.cairo,    IMycode.cairo, etc...

2024-06-26 07:58 UTC, closed without merging