Create  triggerlqtyissuance  updateg  computelqtyperunitstaked functions
blockchain-audit/meridian-starknet pull request #345
Opened 2024-07-07 08:22 UTC by oritlu10

2024-07-07 08:34 UTC, YehudisSternberg requested changes

2024-07-07 08:34 UTC, YehudisSternberg commented on src/pool/stability_pool.cairo
> +function _computeLQTYPerUnitStaked(LQTYIssuance :u256, totalLUSDDeposits :u256) -> (u256) {
הרצת ?
scarb build?
scarb fmt?

2024-07-07 08:40 UTC, oritlu10 commented on src/pool/stability_pool.cairo
> +function _computeLQTYPerUnitStaked(LQTYIssuance :u256, totalLUSDDeposits :u256) -> (u256) {
It has errors on things I didn't do

2024-07-07 08:55 UTC, YehudisSternberg commented on src/pool/stability_pool.cairo
> +function _computeLQTYPerUnitStaked(LQTYIssuance :u256, totalLUSDDeposits :u256) -> (u256) {
but you can only do pr when it al works😉

2024-07-10 07:20 UTC, HadasaHazan approved these changes

2024-07-10 07:20 UTC, merged